namespace OdontoApp.Libraries.Templates
{
    public class HtmlEmailTemplate
    {       
        public static string EmailHead()
        {
            return string.Concat(
            "<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\">",
            "<link href=\"https://fonts.googleapis.com/css2?family=Roboto:wght@300&display=swap\" rel=\"stylesheet\">",
            "<style type=\"text/css\">",
            "    p,",
            "    div {",
            "    font-family: inherit;",
            "    font-size: 14px;",
            "    }",
            "    center {",
            "    color: #000000;",
            "    font-family: 'Roboto' !important, sans-serif;",
            "    }",
            "    center a {",
            "    color: #1188E6;",
            "    text-decoration: none;",
            "    }",
            "    p {",
            "    margin: 0;",
            "    padding: 0;",
            "    }",
            "    table.wrapper {",
            "    width: 100% !important;",
            "    table-layout: fixed;",
            "    -webkit-font-smoothing: antialiased;",
            "    -webkit-text-size-adjust: 100%;",
            "    -moz-text-size-adjust: 100%;",
            "    -ms-text-size-adjust: 100%;",
            "    }",
            "    img.max-width {",
            "    max-width: 100% !important;",
            "    }",
            "    .column.of-2 {",
            "    width: 50%;",
            "    }",
            "    .column.of-3 {",
            "    width: 33.333%;",
            "    }",
            "    .column.of-4 {",
            "    width: 25%;",
            "    }",
            "    @media screen and (max-width:480px) {",
            "    .preheader .rightColumnContent,",
            "    .footer .rightColumnContent {",
            "        text-align: left !important;",
            "    }",
            "    .preheader .rightColumnContent div,",
            "    .preheader .rightColumnContent span,",
            "    .footer .rightColumnContent div,",
            "    .footer .rightColumnContent span {",
            "        text-align: left !important;",
            "    }",
            "    .preheader .rightColumnContent,",
            "    .preheader .leftColumnContent {",
            "        font-size: 80% !important;",
            "        padding: 5px 0;",
            "    }",
            "    table.wrapper-mobile {",
            "        width: 100% !important;",
            "        table-layout: fixed;",
            "    }",
            "    img.max-width {",
            "        height: auto !important;",
            "        max-width: 100% !important;",
            "    }",
            "    a.bulletproof-button {",
            "        display: block !important;",
            "        width: auto !important;",
            "        font-size: 80%;",
            "        padding-left: 0 !important;",
            "        padding-right: 0 !important;",
            "    }",
            "    .columns {",
            "        width: 100% !important;",
            "    }",
            "    .column {",
            "        display: block !important;",
            "        width: 100% !important;",
            "        padding-left: 0 !important;",
            "        padding-right: 0 !important;",
            "        margin-left: 0 !important;",
            "        margin-right: 0 !important;",
            "    }",
            "    }",
            "</style>"
            );
        }
        public static string EmailVerificationBody(string nome, string confirmationLink, string contactLink, string unsubscribeLink)
        {
            return string.Concat(
            "<center class=\"wrapper\" data-link-color=\"#1188E6\""
            ,"    data-body-style=\"font-size:14px; font-family:inherit; color:#000000; background-color:#FFFFFF;\">"
            ,"    <div class=\"webkit\">"
            ,"    <table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" width=\"100%\" class=\"wrapper\" bgcolor=\"#FFFFFF\">"
            ,"        <tbody>"
            ,"        <tr>"
            ,"            <td valign=\"top\" bgcolor=\"#FFFFFF\" width=\"100%\">"
            ,"            <table width=\"100%\" role=\"content-container\" class=\"outer\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\""
            ,"                border=\"0\">"
            ,"                <tbody>"
            ,"                <tr>"
            ,"                   <td width=\"100%\">"
            ,"                    <table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\">"
            ,"                        <tbody>"
            ,"                        <tr>"
            ,"                            <td>"
            ,"                            <table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\""
            ,"                               style=\"width:100%; max-width:600px;\" align=\"center\">"
            ,"                                <tbody>"
            ,"                                <tr>"
            ,"                                    <td role=\"modules-container\""
            ,"                                    style=\"padding:0px 0px 0px 0px; color:#000000; text-align:left;\" bgcolor=\"#FFFFFF\""
            ,"                                    width=\"100%\" align=\"left\">"
            ,"                                    <table class=\"module preheader preheader-hide\" role=\"module\" data-type=\"preheader\""
            ,"                                        border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\""
            ,"                                        style=\"display: none !important; mso-hide: all; visibility: hidden; opacity: 0; color: transparent; height: 0; width: 0;\">"
            ,"                                        <tbody>"
            ,"                                        <tr>"
            ,"                                            <td role=\"module-content\">"
            ,"                                            <p></p>"
            ,"                                            </td>"
            ,"                                        </tr>"
            ,"                                        </tbody>"
            ,"                                    </table>"
            ,"                                    <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" align=\"center\" width=\"100%\""
            ,"                                        role=\"module\" data-type=\"columns\" style=\"padding:30px 20px 30px 20px;\""
            ,"                                        bgcolor=\"#f6f6f6\">"
            ,"                                        <tbody>"
            ,"                                        <tr role=\"module-content\">"
            ,"                                            <td height=\"100%\" valign=\"top\">"
            ,"                                            <table class=\"column\" width=\"540\""
            ,"                                                style=\"width:540px; border-spacing:0; border-collapse:collapse; margin:0px 10px 0px 10px;\""
            ,"                                                cellpadding=\"0\" cellspacing=\"0\" align=\"left\" border=\"0\" bgcolor=\"\">"
            ,"                                                <tbody>"
            ,"                                                <tr>"
            ,"                                                    <td style=\"padding:0px;margin:0px;border-spacing:0;\">"
            ,"                                                    <table class=\"wrapper\" role=\"module\" data-type=\"image\" border=\"0\""
            ,"                                                        cellpadding=\"0\" cellspacing=\"0\" width=\"100%\""
            ,"                                                        style=\"table-layout: fixed;\">"
            ,"                                                        <tbody>"
            ,"                                                        <tr>"
            ,"                                                            <td"
            ,"                                                            style=\"font-size:6px; line-height:10px; padding:0px 0px 0px 0px;\""
            ,"                                                            valign=\"top\" align=\"center\">"
            ,"                                                            <img class=\"max-width\" border=\"0\""
            ,"                                                                style=\"display:block; color:#000000; text-decoration:none; font-family:Helvetica, arial, sans-serif; font-size:16px;\""
            ,"                                                                width=\"200\" alt=\"\""
            ,"                                                                data-proportionally-constrained=\"true\""
            ,"                                                                data-responsive=\"false\""
            ,"                                                                src=\"https://lh3.googleusercontent.com/63mhoH8znFr07UJIZXzXXX2gIAXINbnL9AVhHjgm-qo1ijcMcD3bF1ocrCondF7uZG_QeryYzrYYX2VE6ZuKvbWaJ-KeGNpPSQZHQfuEf0oHiiuQVbSHoBQ-DRaWXJXpvs8y5P_EPdRNgo7nbNsOE_HRbnO5ePjUAjyFxNVj96_0jKxY7wYaJ3Xp28Mn0H5XlPFrMcPna4A9O8jH4Kg9pZBAlwY237G4MJ1x2UVfNKW3I-a04nkuX1OMV-JReQwi2wiYSrD1LMjv2pARE3u6Lc9fvCPnoGNlHT7NeYzXwfQMbNPVoj_Xbkgu2RSipPKiEtjU0nIR5cXlQz6ik_0f23ti3c7SZUOvcizUDFroeZdyJZ_Yjf8HlOKvx7B4UwEiSacWpAoGknYeC_xuO4zslRirIM_8vYvEYArYkHXQuayEWkq4Q1lpizYlMTWNOkj9kPIloi2aXAELe3ejWltJ1F2vBf9MXLSg8G7J5GSGIODd5nRnbdlrLRaOLISBUFFpg2ql_x5qYvHnZNA2tdKDQAYjmzs0ldxP1UMPWFW3MsTEKfLMyPel7AlbGXqea2-3VNuioaQtPGi-6CtA_ZbIgaZ41hsWOAd-emmSN0aPODVITtwuG6kb2qdzpputgHl672he1IllUaj0laUsZf3IIWt-BfzNdqlGw0D277x6g6-BWH0yy1DI6FG-vvyaXw=w796-h266-no?authuser=0\">"
            ,"                                                            </td>"
            ,"                                                        </tr>"
            ,"                                                        </tbody>"
            ,"                                                    </table>"
            ,"                                                    <table class=\"module\" role=\"module\" data-type=\"spacer\" border=\"0\""
            ,"                                                        cellpadding=\"0\" cellspacing=\"0\" width=\"100%\""
            ,"                                                        style=\"table-layout: fixed;\">"
            ,"                                                        <tbody>"
            ,"                                                        <tr>"
            ,"                                                            <td style=\"padding:0px 0px 20px 0px;\" role=\"module-content\""
            ,"                                                            bgcolor=\"\">"
            ,"                                                            </td>"
            ,"                                                        </tr>"
            ,"                                                        </tbody>"
            ,"                                                    </table>"
            ,"                                                    <table class=\"module\" role=\"module\" data-type=\"spacer\" border=\"0\""
            ,"                                                        cellpadding=\"0\" cellspacing=\"0\" width=\"100%\""
            ,"                                                        style=\"table-layout: fixed;\">"
            ,"                                                        <tbody>"
            ,"                                                        <tr>"
            ,"                                                            <td style=\"padding:0px 0px 30px 0px;\" role=\"module-content\""
            ,"                                                            bgcolor=\"\">"
            ,"                                                            </td>"
            ,"                                                        </tr>"
            ,"                                                        </tbody>"
            ,"                                                    </table>"
            ,"                                                    <table class=\"module\" role=\"module\" data-type=\"text\" border=\"0\""
            ,"                                                        cellpadding=\"0\" cellspacing=\"0\" width=\"100%\""
            ,"                                                        style=\"table-layout: fixed;\">"
            ,"                                                        <tbody>"
            ,"                                                        <tr>"
            ,"                                                            <td"
            ,"                                                            style=\"padding:50px 30px 18px 30px; line-height:36px; text-align:inherit; background-color:#ffffff;\""
            ,"                                                            height=\"100%\" valign=\"top\" bgcolor=\"#ffffff\""
            ,"                                                            role=\"module-content\">"
            ,"                                                            <div>"
            ,"                                                                <div style=\"font-family: inherit; text-align: center\">"
            ,"                                                                <span style=\"font-size: 43px\">Olá,"
            ,$"                                                                    {nome} &#128522;!&nbsp;</span>"
            ,"                                                                </div>"
            ,"                                                                <div></div>"
            ,"                                                            </div>"
            ,"                                                            </td>"
            ,"                                                        </tr>"
            ,"                                                        </tbody>"
            ,"                                                    </table>"
            ,"                                                    <table class=\"module\" role=\"module\" data-type=\"text\" border=\"0\""
            ,"                                                        cellpadding=\"0\" cellspacing=\"0\" width=\"100%\""
            ,"                                                        style=\"table-layout: fixed;\">"
            ,"                                                        <tbody>"
            ,"                                                        <tr>"
            ,"                                                            <td"
            ,"                                                            style=\"padding:18px 30px 18px 30px; line-height:22px; text-align:inherit; background-color:#ffffff;\""
            ,"                                                            height=\"100%\" valign=\"top\" bgcolor=\"#ffffff\""
            ,"                                                            role=\"module-content\">"
            ,"                                                            <div>"
            ,"                                                                <div style=\"font-family: inherit; text-align: center\">"
            ,"                                                                <span style=\"font-size: 18px\">Sua conta no OdontoApp"
            ,"                                                                    está quase pronta.</span><br><span"
            ,"                                                                    style=\"color: #000000; font-size: 18px; font-family: arial,helvetica,sans-serif\">"
            ,"                                                                    Para ativá-la, por favor confirme o seu endereço de"
            ,"                                                                    email</span><span style=\"font-size: 18px\">.</span>"
            ,"                                                                </div>"
            ,"                                                            </div>"
            ,"                                                            </td>"
            ,"                                                        </tr>"
            ,"                                                        </tbody>"
            ,"                                                    </table>"
            ,"                                                    <table class=\"module\" role=\"module\" data-type=\"spacer\" border=\"0\""
            ,"                                                        cellpadding=\"0\" cellspacing=\"0\" width=\"100%\""
            ,"                                                        style=\"table-layout: fixed;\">"
            ,"                                                        <tbody>"
            ,"                                                        <tr>"
            ,"                                                            <td style=\"padding:0px 0px 20px 0px;\" role=\"module-content\""
            ,"                                                            bgcolor=\"#ffffff\">"
            ,"                                                            </td>"
            ,"                                                        </tr>"
            ,"                                                        </tbody>"
            ,"                                                    </table>"
            ,"                                                    <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"module\""
            ,"                                                        data-role=\"module-button\" data-type=\"button\" role=\"module\""
            ,"                                                        style=\"table-layout:fixed;\" width=\"100%\">"
            ,"                                                        <tbody>"
            ,"                                                        <tr>"
            ,"                                                            <td align=\"center\" bgcolor=\"#ffffff\" class=\"outer-td\""
            ,"                                                            style=\"padding:0px 0px 0px 0px;\">"
            ,"                                                            <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\""
            ,"                                                                class=\"wrapper-mobile\" style=\"text-align:center;\">"
            ,"                                                                <tbody>"
            ,"                                                                <tr>"
            ,"                                                                    <td align=\"center\" bgcolor=\"#ffbe00\""
            ,"                                                                    class=\"inner-td\""
            ,"                                                                    style=\"border-radius:6px; font-size:16px; text-align:center; background-color:inherit;\">"
            ,$"                                                                    <a href=\"{confirmationLink}\""
            ,"                                                                        style=\"background-color:#1572e8; border:1px solid #1572e8; border-color:#1572e8; border-radius:0px; border-width:1px; color:#ffff; display:inline-block; font-size:14px; font-weight:normal; letter-spacing:0px; line-height:normal; padding:12px 40px 12px 40px; text-align:center; text-decoration:none; border-style:solid; font-family:inherit;\""
            ,"                                                                        target=\"_blank\">Confirmar agora</a>"
            ,"                                                                    </td>"
            ,"                                                                </tr>"
            ,"                                                                </tbody>"
            ,"                                                            </table>"
            ,"                                                            </td>"
            ,"                                                        </tr>"
            ,"                                                        </tbody>"
            ,"                                                    </table>"
            ,"                                                    <table class=\"module\" role=\"module\" data-type=\"spacer\" border=\"0\""
            ,"                                                        cellpadding=\"0\" cellspacing=\"0\" width=\"100%\""
            ,"                                                        style=\"table-layout: fixed;\">"
            ,"                                                        <tbody>"
            ,"                                                        <tr>"
            ,"                                                            <td style=\"padding:0px 0px 50px 0px;\" role=\"module-content\""
            ,"                                                            bgcolor=\"#ffffff\">"
            ,"                                                            </td>"
            ,"                                                        </tr>"
            ,"                                                        </tbody>"
            ,"                                                    </table>"
            ,"                                                    <table class=\"module\" role=\"module\" data-type=\"text\" border=\"0\""
            ,"                                                        cellpadding=\"0\" cellspacing=\"0\" width=\"100%\""
            ,"                                                        style=\"table-layout: fixed;\">"
            ,"                                                        <tbody>"
            ,"                                                        <tr>"
            ,"                                                            <td"
            ,"                                                            style=\"padding:50px 30px 50px 30px; line-height:22px; text-align:inherit; background-color:#6e6e6e;\""
            ,"                                                            height=\"100%\" valign=\"top\" bgcolor=\"#6e6e6e\""
            ,"                                                            role=\"module-content\">"
            ,"                                                            <div>"
            ,"                                                                <div style=\"font-family: inherit; text-align: center\">"
            ,"                                                                <br>"
            ,"                                                                </div>"
            ,"                                                                <div"
            ,"                                                                    style=\"font-family: inherit; text-align: center; width:80%; margin: 0 auto;\">"
            ,"                                                                    <span style=\"color: #ffffff; font-size: 18px\">Se"
            ,"                                                                    você não se cadastrou no OdontoApp recentemente,"
            ,"                                                                    por favor ignore este email.</span>"
            ,"                                                                </div>"
            ,"                                                                <div style=\"font-family: inherit; text-align: center\">"
            ,"                                                                <br>"
            ,"                                                                </div>"
            ,"                                                                <div"
            ,"                                                                    style=\"font-family: inherit; text-align: center; width:80%; margin: 0 auto;\">"
            ,"                                                                    <span"
            ,"                                                                    style=\"color: #ffffff; font-size: 18px;\">Precisa"
            ,"                                                                    de suporte? Nossa equipe está sempre"
            ,"                                                                    pronta para ajudar!</span>"
            ,"                                                                </div>"
            ,"                                                            </div>"
            ,"                                                           </td>"
            ,"                                                        </tr>"
            ,"                                                        </tbody>"
            ,"                                                    </table>"
            ,"                                                    <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"module\""
            ,"                                                        data-role=\"module-button\" data-type=\"button\" role=\"module\""
            ,"                                                        style=\"table-layout:fixed;\" width=\"100%\">"
            ,"                                                        <tbody>"
            ,"                                                        <tr>"
            ,"                                                            <td align=\"center\" bgcolor=\"#6e6e6e\" class=\"outer-td\""
            ,"                                                            style=\"padding:0px 0px 0px 0px;\">"
            ,"                                                            <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\""
            ,"                                                                class=\"wrapper-mobile\" style=\"text-align:center;\">"
            ,"                                                                <tbody>"
            ,"                                                                <tr>"
            ,"                                                                    <td align=\"center\" bgcolor=\"#ffbe00\""
            ,"                                                                    class=\"inner-td\""
            ,"                                                                    style=\"border-radius:6px; font-size:16px; text-align:center; background-color:inherit;\">"
            ,$"                                                                    <a href=\"{contactLink}\""
            ,"                                                                        style=\"background-color:#1572e8; border:1px solid #1572e8; border-color:#1572e8; border-radius:0px; border-width:1px; color:#fff; display:inline-block; font-size:14px; font-weight:normal; letter-spacing:0px; line-height:normal; padding:12px 40px 12px 40px; text-align:center; text-decoration:none; border-style:solid; font-family:inherit;\""
            ,"                                                                        target=\"_blank\">Contate-nos</a>"
            ,"                                                                    </td>"
            ,"                                                                </tr>"
            ,"                                                                </tbody>"
            ,"                                                            </table>"
            ,"                                                            </td>"
            ,"                                                        </tr>"
            ,"                                                        </tbody>"
            ,"                                                    </table>"
            ,"                                                    <table class=\"module\" role=\"module\" data-type=\"spacer\" border=\"0\""
            ,"                                                        cellpadding=\"0\" cellspacing=\"0\" width=\"100%\""
            ,"                                                        style=\"table-layout: fixed;\">"
            ,"                                                        <tbody>"
            ,"                                                        <tr>"
            ,"                                                            <td style=\"padding:0px 0px 30px 0px;\" role=\"module-content\""
            ,"                                                            bgcolor=\"6E6E6E\">"
            ,"                                                            </td>"
            ,"                                                        </tr>"
            ,"                                                        </tbody>"
            ,"                                                    </table>"
            ,"                                                    </td>"
            ,"                                                </tr>"
            ,"                                                </tbody>"
            ,"                                            </table>"
            ,"                                            </td>"
            ,"                                        </tr>"
            ,"                                        </tbody>"
            ,"                                    </table>"
            ,"                                    <div data-role=\"module-unsubscribe\" class=\"module\" role=\"module\""
            ,"                                        data-type=\"unsubscribe\""
            ,"                                        style=\"color:#444444; font-size:12px; line-height:20px; padding:16px 16px 16px 16px; text-align:Center;\">"
            ,"                                        <div class=\"Unsubscribe--addressLine\">"
            ,"                                        <p class=\"Unsubscribe--senderName\" style=\"font-size:12px; line-height:20px;\">"
            ,"                                            Ascore</p>"
            ,"                                        <p style=\"font-size:12px; line-height:20px;\"><span"
            ,"                                            class=\"Unsubscribe--senderAddress\">Av. Santa Luzia"
            ,"                                            183</span>, <span class=\"Unsubscribe--senderCity\">Catu</span>, <span"
            ,"                                            class=\"Unsubscribe--senderState\">Bahia</span> <span"
            ,"                                            class=\"Unsubscribe--senderZip\">48110-000</span></p>"
            ,"                                        </div>"
            ,"                                        <p style=\"font-size:12px; line-height:20px;\"><a"
            ,$"                                            class=\"Unsubscribe--unsubscribeLink\" href=\"{unsubscribeLink}\""
            ,"                                            target=\"_blank\" style=\"text-decoration: none;\">Desinscrever-se</a> - <a"
            ,$"                                            href=\"{unsubscribeLink}\" target=\"_blank\""
            ,"                                            class=\"Unsubscribe--unsubscribePreferences\" style=\"text-decoration: none;\">Cancelar Assinatura</a>"
            ,"                                        </p>"
            ,"                                    </div>"
            ,"                                    </td>"
            ,"                                </tr>"
            ,"                                </tbody>"
            ,"                            </table>"
            ,"                            </td>"
            ,"                        </tr>"
            ,"                        </tbody>"
            ,"                    </table>"
            ,"                    </td>"
            ,"                </tr>"
            ,"                </tbody>"
            ,"            </table>"
            ,"            </td>"
            ,"        </tr>"
            ,"        </tbody>"
            ,"    </table>"
            ,"    </div>"
            ,"</center>"
            );
        }
        public static string EmailRecoveryBody(string nome, string confirmationLink, string contactLink, string unsubscribeLink)
        {
            return string.Concat(
            "<center class=\"wrapper\" data-link-color=\"#1188E6\""
            ,"    data-body-style=\"font-size:14px; font-family:inherit; color:#000000; background-color:#FFFFFF;\">"
            ,"    <div class=\"webkit\">"
            ,"    <table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" width=\"100%\" class=\"wrapper\" bgcolor=\"#FFFFFF\">"
            ,"        <tbody>"
            ,"        <tr>"
            ,"            <td valign=\"top\" bgcolor=\"#FFFFFF\" width=\"100%\">"
            ,"            <table width=\"100%\" role=\"content-container\" class=\"outer\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\""
            ,"                border=\"0\">"
            ,"                <tbody>"
            ,"                <tr>"
            ,"                   <td width=\"100%\">"
            ,"                    <table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\">"
            ,"                        <tbody>"
            ,"                        <tr>"
            ,"                            <td>"
            ,"                            <table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\""
            ,"                               style=\"width:100%; max-width:600px;\" align=\"center\">"
            ,"                                <tbody>"
            ,"                                <tr>"
            ,"                                    <td role=\"modules-container\""
            ,"                                    style=\"padding:0px 0px 0px 0px; color:#000000; text-align:left;\" bgcolor=\"#FFFFFF\""
            ,"                                    width=\"100%\" align=\"left\">"
            ,"                                    <table class=\"module preheader preheader-hide\" role=\"module\" data-type=\"preheader\""
            ,"                                        border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\""
            ,"                                        style=\"display: none !important; mso-hide: all; visibility: hidden; opacity: 0; color: transparent; height: 0; width: 0;\">"
            ,"                                        <tbody>"
            ,"                                        <tr>"
            ,"                                            <td role=\"module-content\">"
            ,"                                            <p></p>"
            ,"                                            </td>"
            ,"                                        </tr>"
            ,"                                        </tbody>"
            ,"                                    </table>"
            ,"                                    <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" align=\"center\" width=\"100%\""
            ,"                                        role=\"module\" data-type=\"columns\" style=\"padding:30px 20px 30px 20px;\""
            ,"                                        bgcolor=\"#f6f6f6\">"
            ,"                                        <tbody>"
            ,"                                        <tr role=\"module-content\">"
            ,"                                            <td height=\"100%\" valign=\"top\">"
            ,"                                            <table class=\"column\" width=\"540\""
            ,"                                                style=\"width:540px; border-spacing:0; border-collapse:collapse; margin:0px 10px 0px 10px;\""
            ,"                                                cellpadding=\"0\" cellspacing=\"0\" align=\"left\" border=\"0\" bgcolor=\"\">"
            ,"                                                <tbody>"
            ,"                                                <tr>"
            ,"                                                    <td style=\"padding:0px;margin:0px;border-spacing:0;\">"
            ,"                                                    <table class=\"wrapper\" role=\"module\" data-type=\"image\" border=\"0\""
            ,"                                                        cellpadding=\"0\" cellspacing=\"0\" width=\"100%\""
            ,"                                                        style=\"table-layout: fixed;\">"
            ,"                                                        <tbody>"
            ,"                                                        <tr>"
            ,"                                                            <td"
            ,"                                                            style=\"font-size:6px; line-height:10px; padding:0px 0px 0px 0px;\""
            ,"                                                            valign=\"top\" align=\"center\">"
            ,"                                                            <img class=\"max-width\" border=\"0\""
            ,"                                                                style=\"display:block; color:#000000; text-decoration:none; font-family:Helvetica, arial, sans-serif; font-size:16px;\""
            ,"                                                                width=\"200\" alt=\"\""
            ,"                                                                data-proportionally-constrained=\"true\""
            ,"                                                                data-responsive=\"false\""
            ,"                                                                src=\"https://lh3.googleusercontent.com/63mhoH8znFr07UJIZXzXXX2gIAXINbnL9AVhHjgm-qo1ijcMcD3bF1ocrCondF7uZG_QeryYzrYYX2VE6ZuKvbWaJ-KeGNpPSQZHQfuEf0oHiiuQVbSHoBQ-DRaWXJXpvs8y5P_EPdRNgo7nbNsOE_HRbnO5ePjUAjyFxNVj96_0jKxY7wYaJ3Xp28Mn0H5XlPFrMcPna4A9O8jH4Kg9pZBAlwY237G4MJ1x2UVfNKW3I-a04nkuX1OMV-JReQwi2wiYSrD1LMjv2pARE3u6Lc9fvCPnoGNlHT7NeYzXwfQMbNPVoj_Xbkgu2RSipPKiEtjU0nIR5cXlQz6ik_0f23ti3c7SZUOvcizUDFroeZdyJZ_Yjf8HlOKvx7B4UwEiSacWpAoGknYeC_xuO4zslRirIM_8vYvEYArYkHXQuayEWkq4Q1lpizYlMTWNOkj9kPIloi2aXAELe3ejWltJ1F2vBf9MXLSg8G7J5GSGIODd5nRnbdlrLRaOLISBUFFpg2ql_x5qYvHnZNA2tdKDQAYjmzs0ldxP1UMPWFW3MsTEKfLMyPel7AlbGXqea2-3VNuioaQtPGi-6CtA_ZbIgaZ41hsWOAd-emmSN0aPODVITtwuG6kb2qdzpputgHl672he1IllUaj0laUsZf3IIWt-BfzNdqlGw0D277x6g6-BWH0yy1DI6FG-vvyaXw=w796-h266-no?authuser=0\">"
            ,"                                                            </td>"
            ,"                                                        </tr>"
            ,"                                                        </tbody>"
            ,"                                                    </table>"
            ,"                                                    <table class=\"module\" role=\"module\" data-type=\"spacer\" border=\"0\""
            ,"                                                        cellpadding=\"0\" cellspacing=\"0\" width=\"100%\""
            ,"                                                        style=\"table-layout: fixed;\">"
            ,"                                                        <tbody>"
            ,"                                                        <tr>"
            ,"                                                            <td style=\"padding:0px 0px 20px 0px;\" role=\"module-content\""
            ,"                                                            bgcolor=\"\">"
            ,"                                                            </td>"
            ,"                                                        </tr>"
            ,"                                                        </tbody>"
            ,"                                                    </table>"
            ,"                                                    <table class=\"module\" role=\"module\" data-type=\"spacer\" border=\"0\""
            ,"                                                        cellpadding=\"0\" cellspacing=\"0\" width=\"100%\""
            ,"                                                        style=\"table-layout: fixed;\">"
            ,"                                                        <tbody>"
            ,"                                                        <tr>"
            ,"                                                            <td style=\"padding:0px 0px 30px 0px;\" role=\"module-content\""
            ,"                                                            bgcolor=\"\">"
            ,"                                                            </td>"
            ,"                                                        </tr>"
            ,"                                                        </tbody>"
            ,"                                                    </table>"
            ,"                                                    <table class=\"module\" role=\"module\" data-type=\"text\" border=\"0\""
            ,"                                                        cellpadding=\"0\" cellspacing=\"0\" width=\"100%\""
            ,"                                                        style=\"table-layout: fixed;\">"
            ,"                                                        <tbody>"
            ,"                                                        <tr>"
            ,"                                                            <td"
            ,"                                                            style=\"padding:50px 30px 18px 30px; line-height:36px; text-align:inherit; background-color:#ffffff;\""
            ,"                                                            height=\"100%\" valign=\"top\" bgcolor=\"#ffffff\""
            ,"                                                            role=\"module-content\">"
            ,"                                                            <div>"
            ,"                                                                <div style=\"font-family: inherit; text-align: center\">"
            ,"                                                                <span style=\"font-size: 43px\">Olá,"
            ,$"                                                                    {nome} &#128522;!&nbsp;</span>"
            ,"                                                                </div>"
            ,"                                                                <div></div>"
            ,"                                                            </div>"
            ,"                                                            </td>"
            ,"                                                        </tr>"
            ,"                                                        </tbody>"
            ,"                                                    </table>"
            ,"                                                    <table class=\"module\" role=\"module\" data-type=\"text\" border=\"0\""
            ,"                                                        cellpadding=\"0\" cellspacing=\"0\" width=\"100%\""
            ,"                                                        style=\"table-layout: fixed;\">"
            ,"                                                        <tbody>"
            ,"                                                        <tr>"
            ,"                                                            <td"
            ,"                                                            style=\"padding:18px 30px 18px 30px; line-height:22px; text-align:inherit; background-color:#ffffff;\""
            ,"                                                            height=\"100%\" valign=\"top\" bgcolor=\"#ffffff\""
            ,"                                                            role=\"module-content\">"
            ,"                                                            <div>"
            ,"                                                                <div style=\"font-family: inherit; text-align: center\">"
            ,"                                                                <span style=\"font-size: 18px\">Recebemos sua solicitação de redefinição de senha."
            ,"                                                                    </span><br><span"
            ,"                                                                    style=\"color: #000000; font-size: 18px; font-family: arial,helvetica,sans-serif\">"
            ,"                                                                    Para redefini-la, por favor clique abaixo</span><span style=\"font-size: 18px\">.</span>"                                                                  
            ,"                                                                </div>"
            ,"                                                            </div>"
            ,"                                                            </td>"
            ,"                                                        </tr>"
            ,"                                                        </tbody>"
            ,"                                                    </table>"
            ,"                                                    <table class=\"module\" role=\"module\" data-type=\"spacer\" border=\"0\""
            ,"                                                        cellpadding=\"0\" cellspacing=\"0\" width=\"100%\""
            ,"                                                        style=\"table-layout: fixed;\">"
            ,"                                                        <tbody>"
            ,"                                                        <tr>"
            ,"                                                            <td style=\"padding:0px 0px 20px 0px;\" role=\"module-content\""
            ,"                                                            bgcolor=\"#ffffff\">"
            ,"                                                            </td>"
            ,"                                                        </tr>"
            ,"                                                        </tbody>"
            ,"                                                    </table>"
            ,"                                                    <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"module\""
            ,"                                                        data-role=\"module-button\" data-type=\"button\" role=\"module\""
            ,"                                                        style=\"table-layout:fixed;\" width=\"100%\">"
            ,"                                                        <tbody>"
            ,"                                                        <tr>"
            ,"                                                            <td align=\"center\" bgcolor=\"#ffffff\" class=\"outer-td\""
            ,"                                                            style=\"padding:0px 0px 0px 0px;\">"
            ,"                                                            <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\""
            ,"                                                                class=\"wrapper-mobile\" style=\"text-align:center;\">"
            ,"                                                                <tbody>"
            ,"                                                                <tr>"
            ,"                                                                    <td align=\"center\" bgcolor=\"#ffbe00\""
            ,"                                                                    class=\"inner-td\""
            ,"                                                                    style=\"border-radius:6px; font-size:16px; text-align:center; background-color:inherit;\">"
            ,$"                                                                    <a href=\"{confirmationLink}\""
            ,"                                                                        style=\"background-color:#1572e8; border:1px solid #1572e8; border-color:#1572e8; border-radius:0px; border-width:1px; color:#ffff; display:inline-block; font-size:14px; font-weight:normal; letter-spacing:0px; line-height:normal; padding:12px 40px 12px 40px; text-align:center; text-decoration:none; border-style:solid; font-family:inherit;\""
            ,"                                                                        target=\"_blank\">Redefinir senha</a>"
            ,"                                                                    </td>"
            ,"                                                                </tr>"
            ,"                                                                </tbody>"
            ,"                                                            </table>"
            ,"                                                            </td>"
            ,"                                                        </tr>"
            ,"                                                        </tbody>"
            ,"                                                    </table>"
            ,"                                                    <table class=\"module\" role=\"module\" data-type=\"spacer\" border=\"0\""
            ,"                                                        cellpadding=\"0\" cellspacing=\"0\" width=\"100%\""
            ,"                                                        style=\"table-layout: fixed;\">"
            ,"                                                        <tbody>"
            ,"                                                        <tr>"
            ,"                                                            <td style=\"padding:0px 0px 50px 0px;\" role=\"module-content\""
            ,"                                                            bgcolor=\"#ffffff\">"
            ,"                                                            </td>"
            ,"                                                        </tr>"
            ,"                                                        </tbody>"
            ,"                                                    </table>"
            ,"                                                    <table class=\"module\" role=\"module\" data-type=\"text\" border=\"0\""
            ,"                                                        cellpadding=\"0\" cellspacing=\"0\" width=\"100%\""
            ,"                                                        style=\"table-layout: fixed;\">"
            ,"                                                        <tbody>"
            ,"                                                        <tr>"
            ,"                                                            <td"
            ,"                                                            style=\"padding:50px 30px 50px 30px; line-height:22px; text-align:inherit; background-color:#6e6e6e;\""
            ,"                                                            height=\"100%\" valign=\"top\" bgcolor=\"#6e6e6e\""
            ,"                                                            role=\"module-content\">"
            ,"                                                            <div>"
            ,"                                                                <div style=\"font-family: inherit; text-align: center\">"
            ,"                                                                <br>"
            ,"                                                                </div>"
            ,"                                                                <div"
            ,"                                                                    style=\"font-family: inherit; text-align: center; width:80%; margin: 0 auto;\">"
            ,"                                                                    <span style=\"color: #ffffff; font-size: 18px\">"
            ,"                                                                    Se você não realizou um pedido de redefinição de senha, por favor ignore este email."
            ,"                                                                    </span>"
            ,"                                                                </div>"
            ,"                                                                <div style=\"font-family: inherit; text-align: center\">"
            ,"                                                                <br>"
            ,"                                                                </div>"
            ,"                                                                <div"
            ,"                                                                    style=\"font-family: inherit; text-align: center; width:80%; margin: 0 auto;\">"
            ,"                                                                    <span"
            ,"                                                                    style=\"color: #ffffff; font-size: 18px;\">Precisa"
            ,"                                                                    de suporte? Nossa equipe está sempre"
            ,"                                                                    pronta para ajudar!</span>"
            ,"                                                                </div>"
            ,"                                                            </div>"
            ,"                                                           </td>"
            ,"                                                        </tr>"
            ,"                                                        </tbody>"
            ,"                                                    </table>"
            ,"                                                    <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"module\""
            ,"                                                        data-role=\"module-button\" data-type=\"button\" role=\"module\""
            ,"                                                        style=\"table-layout:fixed;\" width=\"100%\">"
            ,"                                                        <tbody>"
            ,"                                                        <tr>"
            ,"                                                            <td align=\"center\" bgcolor=\"#6e6e6e\" class=\"outer-td\""
            ,"                                                            style=\"padding:0px 0px 0px 0px;\">"
            ,"                                                            <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\""
            ,"                                                                class=\"wrapper-mobile\" style=\"text-align:center;\">"
            ,"                                                                <tbody>"
            ,"                                                                <tr>"
            ,"                                                                    <td align=\"center\" bgcolor=\"#ffbe00\""
            ,"                                                                    class=\"inner-td\""
            ,"                                                                    style=\"border-radius:6px; font-size:16px; text-align:center; background-color:inherit;\">"
            ,$"                                                                    <a href=\"{contactLink}\""
            ,"                                                                        style=\"background-color:#1572e8; border:1px solid #1572e8; border-color:#1572e8; border-radius:0px; border-width:1px; color:#fff; display:inline-block; font-size:14px; font-weight:normal; letter-spacing:0px; line-height:normal; padding:12px 40px 12px 40px; text-align:center; text-decoration:none; border-style:solid; font-family:inherit;\""
            ,"                                                                        target=\"_blank\">Contate-nos</a>"
            ,"                                                                    </td>"
            ,"                                                                </tr>"
            ,"                                                                </tbody>"
            ,"                                                            </table>"
            ,"                                                            </td>"
            ,"                                                        </tr>"
            ,"                                                        </tbody>"
            ,"                                                    </table>"
            ,"                                                    <table class=\"module\" role=\"module\" data-type=\"spacer\" border=\"0\""
            ,"                                                        cellpadding=\"0\" cellspacing=\"0\" width=\"100%\""
            ,"                                                        style=\"table-layout: fixed;\">"
            ,"                                                        <tbody>"
            ,"                                                        <tr>"
            ,"                                                            <td style=\"padding:0px 0px 30px 0px;\" role=\"module-content\""
            ,"                                                            bgcolor=\"6E6E6E\">"
            ,"                                                            </td>"
            ,"                                                        </tr>"
            ,"                                                        </tbody>"
            ,"                                                    </table>"
            ,"                                                    </td>"
            ,"                                                </tr>"
            ,"                                                </tbody>"
            ,"                                            </table>"
            ,"                                            </td>"
            ,"                                        </tr>"
            ,"                                        </tbody>"
            ,"                                    </table>"
            ,"                                    <div data-role=\"module-unsubscribe\" class=\"module\" role=\"module\""
            ,"                                        data-type=\"unsubscribe\""
            ,"                                        style=\"color:#444444; font-size:12px; line-height:20px; padding:16px 16px 16px 16px; text-align:Center;\">"
            ,"                                        <div class=\"Unsubscribe--addressLine\">"
            ,"                                        <p class=\"Unsubscribe--senderName\" style=\"font-size:12px; line-height:20px;\">"
            ,"                                            Ascore</p>"
            ,"                                        <p style=\"font-size:12px; line-height:20px;\"><span"
            ,"                                            class=\"Unsubscribe--senderAddress\">Av. Santa Luzia"
            ,"                                            183</span>, <span class=\"Unsubscribe--senderCity\">Catu</span>, <span"
            ,"                                            class=\"Unsubscribe--senderState\">Bahia</span> <span"
            ,"                                            class=\"Unsubscribe--senderZip\">48110-000</span></p>"
            ,"                                        </div>"
            ,"                                        <p style=\"font-size:12px; line-height:20px;\"><a"
            ,$"                                            class=\"Unsubscribe--unsubscribeLink\" href=\"{unsubscribeLink}\""
            ,"                                            target=\"_blank\" style=\"text-decoration: none;\">Desinscrever-se</a> - <a"
            ,$"                                            href=\"{unsubscribeLink}\" target=\"_blank\""
            ,"                                            class=\"Unsubscribe--unsubscribePreferences\" style=\"text-decoration: none;\">Cancelar Assinatura</a>"
            ,"                                        </p>"
            ,"                                    </div>"
            ,"                                    </td>"
            ,"                                </tr>"
            ,"                                </tbody>"
            ,"                            </table>"
            ,"                            </td>"
            ,"                        </tr>"
            ,"                        </tbody>"
            ,"                    </table>"
            ,"                    </td>"
            ,"                </tr>"
            ,"                </tbody>"
            ,"            </table>"
            ,"            </td>"
            ,"        </tr>"
            ,"        </tbody>"
            ,"    </table>"
            ,"    </div>"
            ,"</center>"
            );
        }
        public static string EmailHtml(string head, string body)
        {
            return string.Concat(head,body);
        }
    }
}